## Yolov7
weights: './yolov7/weights/yolov7x.pt' # model.pt path(s)
source: 'data/boat4' # source  # file/folder, 0 for webcam
img_size: 1280 # inference size (pixels)
conf_thres: 0.25 # object confidence threshold
iou_thres: 0.45 # IOU threshold for NMS
device: '' # cuda device, i.e. 0 or 0,1,2,3 or cpu
view_img: False # display results
save_txt: False # save results to *.txt
save_conf: False # save confidences in --save-txt labels
nosave: True # do not save images/videos
classes:  # filter by class: --class 0, or --class 0 2 3
agnostic_nms: False # class-agnostic NMS
augment: False # augmented inference
update: False # update all models
project: 'output' # save results to project/name
name: 'boat4' # save results to project/name
exist_ok: True # existing project/name ok, do not increment
no_trace: True # don't trace model

## OSTrack
tracker: 'ostrack'
tracker_params: 'vitb_384_mae_ce_32x4_ep300'
threshold_conf: 1.0
threshold_iou: 0.5

## Results
save_video: False